version: '3.8'

services:
  portfolio-app:
    build: .
    container_name: portfolio-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - portfolio-net

networks:
  portfolio-net:
    driver: bridge